### ISSUE TITLE
Unable to authenticate to Engage with GH OAuth

### ISSUE THREAD

**Issue by AdmiralAsshat** [kororaproject/kp-canvas#16]
I setup an Engage account using the "Sign In with Github" feature, rather than constructing one from scratch. I do not seem to be able to authenticate to the Engage server as a result when trying to add a template.

`$ canvas template add AdmiralAsshat:laptop --user AdmiralAsshat`
`Password (AdmiralAsshat): `

```
ERROR:root:error: unable to authenticate
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/canvas/cli/commands/template.py", line 105, in run_add
    res = self.cs.template_create(t)
  File "/usr/lib/python3.6/site-packages/canvas/service.py", line 393, in template_create
    self.authenticate()
  File "/usr/lib/python3.6/site-packages/canvas/service.py", line 172, in authenticate
    raise ServiceException('unable to authenticate')
canvas.service.ServiceException: error: unable to authenticate
```

**Comment by firnsy** [comment]
Ah, you'll need to set a password to auth with canvas.

**Comment by jimkp** [comment]
It isn't possible to reset the password either as the user or with my Admin login. It appears to accept it but then says unable to reset password.
